spring:
  datasource:
    url: jdbc:postgresql://10.192.72.79:5432/wecity
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post@123
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL